# Generated by Django 5.0 on 2025-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user_answer',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
